language: node_js

node_js:
  - "14.9.0"

cache: yarn 

install:
  - yarn install

script:
  - npm test
  - npm run build 
  - npm run travis

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
