language: node_js

node_js:
  - "5.0"
  - "5.1.1"
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "5.7.1"
  - "5.8.0"

cache: yarn 

install:
  - yarn ci

script:
  - yarn test
  - yarn run build 

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: yongkang0312
