language: node_js

node_js:
  - "14.9.0"
  - "14.8.0"
  - "14.7.0"
  - "14.6.0"
  - "14.5.0"
  - "14.4.0"
  - "14.3.0"
  - "14.2.0"

cache: yarn 

install:
  - yarn ci

script:
  - yarn test
  - yarn run build 

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
